#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : ding-libs
Version  : 0.4.0
Release  : 3
URL      : https://github.com/SSSD/ding-libs/archive/ding_libs-0_4_0.tar.gz
Source0  : https://github.com/SSSD/ding-libs/archive/ding_libs-0_4_0.tar.gz
Summary  : A dynamically-growing, reference-counted array
Group    : Development/Tools
License  : GPL-3.0 LGPL-3.0
Requires: ding-libs-lib
Requires: ding-libs-license
BuildRequires : pkgconfig(check)

%description
To build the ding-libs from the tarball:
./configure
make
make docs (optional)
make check (optional)
make install

%package dev
Summary: dev components for the ding-libs package.
Group: Development
Requires: ding-libs-lib
Provides: ding-libs-devel

%description dev
dev components for the ding-libs package.


%package doc
Summary: doc components for the ding-libs package.
Group: Documentation

%description doc
doc components for the ding-libs package.


%package lib
Summary: lib components for the ding-libs package.
Group: Libraries
Requires: ding-libs-license

%description lib
lib components for the ding-libs package.


%package license
Summary: license components for the ding-libs package.
Group: Default

%description license
license components for the ding-libs package.


%prep
%setup -q -n ding-libs-ding_libs-0_4_0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1535910007
%reconfigure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1535910007
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/ding-libs
cp COPYING %{buildroot}/usr/share/doc/ding-libs/COPYING
cp COPYING.LESSER %{buildroot}/usr/share/doc/ding-libs/COPYING.LESSER
%make_install

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/*.h
/usr/lib64/libbasicobjects.so
/usr/lib64/libcollection.so
/usr/lib64/libdhash.so
/usr/lib64/libini_config.so
/usr/lib64/libpath_utils.so
/usr/lib64/libref_array.so
/usr/lib64/pkgconfig/basicobjects.pc
/usr/lib64/pkgconfig/collection.pc
/usr/lib64/pkgconfig/dhash.pc
/usr/lib64/pkgconfig/ini_config.pc
/usr/lib64/pkgconfig/path_utils.pc
/usr/lib64/pkgconfig/ref_array.pc

%files doc
%defattr(0644,root,root,0755)
%doc /usr/share/doc/ding\-libs/*

%files lib
%defattr(-,root,root,-)
/usr/lib64/libbasicobjects.so.0
/usr/lib64/libbasicobjects.so.0.1.0
/usr/lib64/libcollection.so.4
/usr/lib64/libcollection.so.4.0.0
/usr/lib64/libdhash.so.1
/usr/lib64/libdhash.so.1.0.2
/usr/lib64/libini_config.so.5
/usr/lib64/libini_config.so.5.0.0
/usr/lib64/libpath_utils.so.1
/usr/lib64/libpath_utils.so.1.0.1
/usr/lib64/libref_array.so.1
/usr/lib64/libref_array.so.1.2.0

%files license
%defattr(-,root,root,-)
/usr/share/doc/ding-libs/COPYING
/usr/share/doc/ding-libs/COPYING.LESSER
